### PR TITLE
ENH: Added a note about odd padding with centering

### PR DESCRIPTION
**Pull request by madphysicist**

### CODE REVIEW

**Comment by Akuli** [comment]
I'm feeling like most people probably don't care about which side the extra padding character ends up in, and the people who care will probably find it easily enough from the official documentation.

**Comment by madphysicist** [comment]
Fair enough. I did not see it in the official documentation, but that's probably my fault, not the documentation's.

**Comment by ulope** [comment]
Thanks for the PR. I think it's useful to mention. 
However the question is if that behavior is specified or just an implementation detail of particular versions of Python.

**Comment by madphysicist** [comment]
That's a very interesting point. I will do some research and find out.

**Comment by madphysicist** [comment]
Just for the record, here is my pending research :) http://stackoverflow.com/questions/41050445/center-alignment-print-format-specifier-implementation-detail. Hopefully someone in the know will come up with an answer instead of shutting the question down.

**Comment by ulope** [comment]
Thanks!

**Pull request merged**
