### PR TITLE
Updated tests/test_content.py - Added the "staircase example"

### PR DESCRIPTION
**Pull request by olgam-**
This example prints to the screen a staircase that goes from down left to up right.
The user defines how big they want the staircase to be and the program prints sufficient blank spaces in front of the correct amount of hashtag keys(#). This formatting works for all staircase lengths as provided by user.

### CODE REVIEW

**Comment by zerok** [comment]
Hi :)

This is a padding example, right?

There are, sadly, a couple of issues with your code. First of all, it doesn't include an example for non-format string-formatting, the code uses raw_input which doesn't work in a unittest-context all that well, and isn't correctly indented. 

Could you please try to fix those? :)

**Comment by olgam-** [comment]
I think I solved the above problems. Let me know if there is something more I should change. I am a Github newbie and now I'm starting to learn. :)

**Comment by ulope** [comment]
Thanks for taking the time to submit this. New content is always welcome.

Having said this I don't think this particular example fits very well with the rest of the page's current content. At the moment all examples we have are very trimmed down to focus only on the formatting aspect of things. Your addition goes a bit beyond that into a "semi real word" example territory.

So while I'm pretty strongly against adding this example to the page as it currently is it might be a good idea if we added a section or even another page for examples of this kind. This can of course be tricky since such pages can devolve into 'snippet graves' pretty quickly.

@zerok what do you think?

**Comment by zerok** [comment]
Sorry for being so late here. 

@olgam- It looks like a mix of padding and alignment to me which is something we already have an example for (test_string_pad_align). 

In general I agree with @ulope. We should focus on extremely tight examples but also extend our contribution guide to make it easier to contribute and how to do that to avoid the problems you were facing here :)

The current implementation of the site relies on using pytest for making sure that all examples work across multiple Python versions. We both have worked with pytest for quite a while and therefore completely forgot to document that part within the contribution guidelines. Sorry about that :disappointed:  

Regarding the concrete example here, (as I said above) I think it's already covered with the alignment/padding examples. Sorry :cry:

**Pull request closed without merging**
